name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        **Speculated performance issues will be marked as invalid and closed if they do not come with actual profiling data + analysis supporting the claim.**
        
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        To rule out invalid issues, confirm and check each one of the checkboxes.
      options:
        - label: I have read the **issue reporting section** in the [contributing guidelines](https://github.com/qbittorrent/qBittorrent/blob/master/CONTRIBUTING.md), so I know how to submit a good bug report with the required information
          required: true
        - label: I have verified that the **issue is not fixed and is reproducible** in the **[latest version](https://www.qbittorrent.org/download.php)**
          required: true
        - label: (optional but recommended) I have verified that the **issue is not fixed and is reproducible** in the **[latest CI build](https://github.com/qbittorrent/qBittorrent/actions/workflows/ci.yaml?query=branch%3Amaster+event%3Apush)**
          required: false
        - label: I have **checked the [frequent/common issues list](https://github.com/qbittorrent/qBittorrent/projects/2)** and **searched** the issue tracker for similar bug reports (including closed ones) **to avoid posting a duplicate**
          required: true
        - label: This report is **not a support request or question**, both of which are better suited for either the [discussions section](https://github.com/qbittorrent/qBittorrent/discussions), [forum](https://qbforums.shiki.hu/), or [subreddit](https://www.reddit.com/r/qBittorrent/). The [wiki](https://github.com/qbittorrent/qBittorrent/wiki) did not contain a suitable solution either.
          required: true

- type: input
    attributes:
      label: Operating System and version
    validations:
      required: true

- type: input
    attributes:
      label: (If Linux) Please give Qt & libtorrent version
    validations:
      required: true

  - type: input
    attributes:
      label: qBittorrent version
    validations:
      required: true

  - type: input
    attributes:
      label: If WebUI related (Browser name and version)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Please give a clear and concise description of the bug/issue
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please walk us thorugh it with  a clear and concise description
      placeholder: |
        1. [First Step]
        2. [Second Step]
        3. [and so on...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: Please give a clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behavior
      description: Please give a clear and concise description of what actually happened
    validations:
      required: true
