name: GitHub Actions file health check

on: [pull_request, push]

jobs:
  check_file_health:
    name: Check file health

    runs-on: ubuntu-20.04

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: install zsh
      run: |
        sudo apt update
        sudo apt list --upgradable
        sudo apt install zsh

    - name: run check file health script
      run: |
        ./.github/workflows/file_health.sh
