name: WebUI CI

on: [pull_request, push]

jobs:
  check_webui:
    name: Check WebUI
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src/webui/www

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: setup nodejs
      uses: actions/setup-node@v2
      with:
       node-version: lts/*
       check-latest: true

    - name: install tools
      run: npm install

    - name: lint code
      run: npm run lint

    - name: format code
      run: |
        npm run format
        git diff --exit-code
